POST http://localhost:4000/users/
Content-Type: multipart/form-data; boundary=SOMERANDOMTEXT

--SOMERANDOMTEXT
Content-Disposition: form-data; name="user"
Content-Type: application/json

{
    "id": 1,
    "name": "Edgar Endo", 
    "course": "CS572",
    "grade": 95
}
--SOMERANDOMTEXT
Content-Disposition: form-data; name="picture"; filename="myPic.jpg"
Content-Type: image/jpeg

< ./myPic.jpeg

--SOMERANDOMTEXT--
